export interface ILayoutElements {
  yellowCircle: boolean;
  yellowCircle2: boolean;
  orangeHex: boolean;
  grayTriangle: boolean;
  pinkTriangle: boolean;
  blueHex: boolean;
  redCircle: boolean;
  yellowSquare: boolean;
  blueSquare: boolean;
  heroBG: boolean;
  firstMidBG: boolean;
  secMidBG: boolean;
  cube: boolean;
  graph: boolean;
  card: boolean;
  leftCloud: boolean;
  rightCloud: boolean;
  flower: boolean;
  coin: boolean;
  chat: boolean;
  ball: boolean;
  pinkChart: boolean;
  blueCube: boolean;
  leftSemicircle: boolean;
  rightSemicircle: boolean;
  facebookIcon: boolean;
  instagramIcon: boolean;
}
